spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # BLOCK internal endpoints from outside (common for all envs)
        - id: block-internal
          uri: no://op
          predicates:
            - Path=/internal/**
          filters:
            - SetStatus=403

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true