server:
  port: ${USER_SERVICE_PORT:9090}

spring:
  application:
    name: user-service

  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${USER_DB_USERNAME:postgres}
    password: ${USER_DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  issuer: ${JWT_ISSUER:ecommerce-auth}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true